name: Pipeline Express
on: [push]

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Ejecutar script
        run: python script.py

      - name: Subir artefacto
        uses: actions/upload-artifact@v3
        with:
          name: resultados
          path: resultados.txt

      - name: Notificar
        run: |
          echo "🎉 Pipeline completado!"
          echo "Descarga los resultados en la pestaña 'Artifacts'"
